<a href="https://colab.research.google.com/github/abdullah-621/pandas/blob/main/Copy_of_task_21.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

###`Q-1:` You are given a Multi index DataFrame. You task is to swap level-0 index with level-0 column.
* Change Branch -> ('cse', 'ece') as columns at level-0 and ('delhi'	'mumbai') as level-0 Index
* And Sort on row index level-0

In [18]:
# Given Code Snippets
index_val = [('cse',2019),('cse',2020),('cse',2021),('cse',2022),('ece',2019),('ece',2020),('ece',2021),('ece',2022)]
multiindex = pd.MultiIndex.from_tuples(index_val)
df = pd.DataFrame(
    [
        [1,2,0,0],
        [3,4,0,0],
        [5,6,0,0],
        [7,8,0,0],
        [9,10,0,0],
        [11,12,0,0],
        [13,14,0,0],
        [15,16,0,0],
    ],
    index = multiindex,
    columns = pd.MultiIndex.from_product([['delhi','mumbai'],['avg_package','students']])
)

df

               delhi               mumbai
         avg_package students avg_package students
cse 2019           1        2           0        0
    2020           3        4           0        0
    2021           5        6           0        0
    2022           7        8           0        0
ece 2019           9       10           0        0
    2020          11       12           0        0
    2021          13       14           0        0
    2022          15       16           0        0

In [77]:
# # code here
# df.stack(level=0,future_stack=True).unstack(level = 0).sort_index(level=0, ascending=False)

df.stack(future_stack=True, level=0).unstack(level = 0).swaplevel().swaplevel(axis=1).sort_index(ascending=True)

                    cse         ece      cse      ece
            avg_package avg_package students students
delhi  2019           1           9        2       10
       2020           3          11        4       12
       2021           5          13        6       14
       2022           7          15        8       16
mumbai 2019           0           0        0        0
       2020           0           0        0        0
       2021           0           0        0        0
       2022           0           0        0        0

###`Q-2:` Covid Cases Data Set Problem
 Make a DataFrame Using both Covid Dataset. With Country name as Level-0 and Provinance/State as Level-1 Index and date, No of cases and No of Deaths as Columns.

In [84]:
confirm = pd.read_csv('https://docs.google.com/spreadsheets/d/e/2PACX-1vTmqT3kxd0i0RUFiEnwA1Hboiunv28MeNTatZsIEqlPPB7mHrl0ttJL7utZ23_1s5FW8ZjODmB8jHIi/pub?gid=2142019845&single=true&output=csv')

deaths = pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vQn4nLCKIVZMw4e89YeRqgKaSAAwRFaZ6ILMW_FUejZ2tkv3Np1f9gD4QOl3ASHeLzWjOjfmLDKcCOF/pub?gid=212966958&single=true&output=csv")

# confirm.head()
# deaths.head()

In [104]:
df_confirm = confirm.melt(id_vars = ['Province/State',	'Country/Region',	'Lat',	'Long'], var_name = 'Date', value_name="num_cases")
df_deaths = deaths.melt(id_vars = ['Province/State',	'Country/Region',	'Lat',	'Long'], var_name = 'Date', value_name="num_deaths")

df_index = pd.merge(df_confirm, df_deaths, on = ['Province/State',	'Country/Region',	'Lat',	'Long', 'Date']).set_index(['Province/State','Country/Region','num_cases'])

df_index

                                                     Lat        Long     Date  \
Province/State Country/Region       num_cases
NaN            Afghanistan          0          33.939110   67.709953  1/22/20
               Albania              0          41.153300   20.168300  1/22/20
               Algeria              0          28.033900    1.659600  1/22/20
               Andorra              0          42.506300    1.521800  1/22/20
               Angola               0         -11.202700   17.873900  1/22/20
...                                                  ...         ...      ...
               West Bank and Gaza   703228     31.952200   35.233200   1/2/23
               Winter Olympics 2022 535        39.904200  116.407400   1/2/23
               Yemen                11945      15.552727   48.516388   1/2/23
               Zambia               334661    -13.133897   27.849332   1/2/23
               Zimbabwe             259981    -19.015438   29.154857   1/2/23

                                               num_deaths
Province/State Country/Region       num_cases
NaN            Afghanistan          0                   0
               Albania              0                   0
               Algeria              0                   0
               Andorra              0                   0
               Angola               0                   0
...                                                   ...
               West Bank and Gaza   703228           5708
               Winter Olympics 2022 535                 0
               Yemen                11945            2159
               Zambia               334661           4024
               Zimbabwe             259981           5637

[311253 rows x 4 columns]

###`Q-3:` Show Country with Heighest death percent out of confirmed Cases.

In [5]:
# code here

### `Q-4` : Make a dataframe for India from Covid Data with one extra column representing no of new cases.

* Just for Assumption "No of new cases" will be equal to difference of "no of cases" with previous day.
* First day new cases will be NaN or equal to no of cases

Say on 12/30/22 No of cases is - 44679608	and a day previous (12/29/22) no of cases is - 44679382.

Then for 12/30/22 -> No of New Cases  = 44679608 - 44679382 =

Note:- Try using shift Function

Try using the shift function

```
s = pd.Series([1,2,3,4,5,6])
s #-> [1,2,3,4,5,6]
s.shift(1) #-> [NaN, 1,2,3,4,5]
s.shift(-1) #-> [2,3,4,5,6, NaN]
```

In [6]:
# code here

### `Q-5:` Read the Dataset using the below given link and create a multi-index dataframe using the columns "Country" and "City/Town".

This dataset is about the most polluted cities in the world. You can get details from [here](https://www.kaggle.com/datasets/rajkumarpandey02/worlds-most-air-polluted-countries-cities).

**Dataset link:** https://tinyurl.com/2fe6vz4u Directly use this link to read.

**Task:**
1. Find out the name of the city of India which is most poluted based on PM10.
2. Find out the name of the city of India which has minumum pollution level based on PM10.
3. Do same operations (like 1 and 2) with the country China.
4. Make a pie chart based on the column "PM10" of the country Poland.
5. Make a bar chart based on the columns "PM2.5" and "PM10" of the countries Israel and Qatar.
6. Convert this MultiIndex DataFrame to Series by retaining the informations.

In [7]:
# code here