<a href="https://colab.research.google.com/github/abdullah-621/pandas/blob/main/session_19_tasks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Questions based on Titanic Dataset:**

To read the dataset as csv, use the below code:

```python
import pandas as pd

url = "https://docs.google.com/spreadsheets/d/e/2PACX-1vQjh5HzZ1N0SU7ME9ZQRzeVTaXaGsV97rU8R7eAcg53k27GTstJp9cRUOfr55go1GRRvTz1NwvyOnuh/pub?gid=1562145139&single=true&output=csv"
titanic_df = pd.read_csv(url)
```

In [1]:
import pandas as pd

url = "https://docs.google.com/spreadsheets/d/e/2PACX-1vQjh5HzZ1N0SU7ME9ZQRzeVTaXaGsV97rU8R7eAcg53k27GTstJp9cRUOfr55go1GRRvTz1NwvyOnuh/pub?gid=1562145139&single=true&output=csv"
titanic_df = pd.read_csv(url)

### `Q-1:` Using `groupby` make groups using the `"Pclass"` column and find out the average age and total number of missing values in the `"Age"` column for every group.

In [2]:
# code here
temp_df = titanic_df.groupby('Pclass')
temp_df['Age'].mean()

Pclass
1    38.233441
2    29.877630
3    25.140620
Name: Age, dtype: float64

In [3]:
temp_df['Age'].apply(lambda x : x.isna().sum())

Pclass
1     30
2     11
3    136
Name: Age, dtype: int64

### `Q-2:` Using `groupby` make groups using the `"Pclass"` column and fill every group's `"Embarked"` column's missing values with the mode value of that group. After that, print every group's `"Embarked"` column's value counts in ascending order.

In [25]:
# code here
temp_df = titanic_df.groupby('Pclass').median(numeric_only=True)
temp_df

        PassengerId  Survived   Age  SibSp  Parch     Fare
Pclass
1             472.0       1.0  37.0    0.0    0.0  60.2875
2             435.5       0.0  29.0    0.0    0.0  14.2500
3             432.0       0.0  24.0    0.0    0.0   8.0500

### `Q-3:` Make groups based on `"Embarked"` column. And for each of this embarked group, make another group based on `"Pclass"` and find out the average fare (round off up to 2 decimal places) for each "Pclass" for each group of "Embarked".

**Sample Output:**

```bash
{'C': {1: 105, 2: 25, 3: 11},
 'Q': {1: 90, 2: 12, 3: 11},
 'S': {1: 70, 2: 20, 3: 15}}
```

In [34]:
# code here
result = titanic_df.groupby(['Embarked','Pclass'])['Fare'].mean().round(2)
result

Embarked  Pclass
C         1         104.72
          2          25.36
          3          11.21
Q         1          90.00
          2          12.35
          3          11.18
S         1          70.36
          2          20.33
          3          14.64
Name: Fare, dtype: float64

## **Questions Based on Fifa Worldcup - 2022 Dataset:**

You can read the dataset by using the below sample code

```python
import pandas as pd

fifa_df = pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vT3D_x_4DS6d51LKJ7ze1sxT5WpV5uiSVOFYHLwBiGru6vFyVv5h5-83AwFjxWYiWfCDjDAaarHAV-k/pub?gid=0&single=true&output=csv")
```

In [63]:
import pandas as pd

fifa_df = pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vT3D_x_4DS6d51LKJ7ze1sxT5WpV5uiSVOFYHLwBiGru6vFyVv5h5-83AwFjxWYiWfCDjDAaarHAV-k/pub?gid=0&single=true&output=csv")

### `Q-4:` Perform `groupby` based on the `"Team"` column and then perform Z Normalization on top of the below columns of each group:
1. Passes
2. Passes Completed
3. Attempted Line Breaks
4. Completed Line Breaks

You have to make a python function named `z_normalization` which takes two arguments:

1. *group:* Every group that you have created
2. *cols_to_perform:* This parameter takes a list of columns on which you have to perform the Z-Normalization.

For this problem, you have to use th `apply()` method.

$\Large Z \ - \ Normalization = \frac{X_i - \mu}{std} $

After that find out the below values for each group:
- minimum "Passess"
- maximum "Passess"
- minimum "Yellow Cards"
- maximum "Yellow cards"
- average "Yellow Cards"
- maximum "Attempted Line Breaks"
- minimum "Attempted Line Breaks"
- standardard deviation of "Attempted Line Breaks"
- average Possession

In [77]:
# code here
def nomalized(group):
  group['Passes_normal'] = (group['Passes'] - group['Passes'].min()) / (group['Passes'].max() - group['Passes'].min())
  group['Passes Completed_normal'] = (group['Passes Completed'] - group['Passes Completed'].min()) / (group['Passes Completed'].max() - group['Passes Completed'].min())
  group['Attempted Line Breaks_normal'] = (group['Attempted Line Breaks'] - group['Attempted Line Breaks'].min()) / (group['Attempted Line Breaks'].max() - group['Attempted Line Breaks'].min())
  group['Completed Line Breaks_normal'] = (group['Completed Line Breaks'] - group['Completed Line Breaks'].min()) / (group['Completed Line Breaks'].max() - group['Completed Line Breaks'].min())

  return group

temp_df = fifa_df.groupby("Team").apply(nomalized)

result = temp_df.agg(
    {
        "Passes" : ['min', 'max'],
        "Yellow Cards" : ['min', 'max', 'mean'],
        "Attempted Line Breaks" : ['max', 'min', 'std'],
        "Possession (%)" : 'mean'
    }
).round(2)

result

/tmp/ipython-input-3986554358.py:10: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_df = fifa_df.groupby("Team").apply(nomalized)

      Passes  Yellow Cards  Attempted Line Breaks  Possession (%)
min    225.0          0.00                  56.00             NaN
max   1070.0          8.00                 259.00             NaN
mean     NaN          1.73                    NaN           43.48
std      NaN           NaN                  34.12             NaN

## **Questions on IPL wala dataset**

ball by ball dataset - https://drive.google.com/file/d/1-kvv_9KCSAFWcrhS9WgTxSrURkRh6GNt/view?usp=share_link

###`Q-5:` Find batsman in below category-
* Highest score while chasing
* Best Strike rate while chasing and have faced 100+ balls


> Chasing mean team batting in second inning

In [80]:
ipl = pd.read_csv("/content/ipl_deliveries - ipl_deliveries.csv")
ipl.head()

,ID,Team,innings,overs,ballnumber,batter,bowler,non-striker,extra_type,batsman_run,extras_run,total_run,non_boundary,isWicketDelivery,player_out,kind,fielders_involved,BattingTeam,BowlingTeam
0,1312200,Rajasthan RoyalsGujarat Titans,1,0,1,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
1,1312200,Rajasthan RoyalsGujarat Titans,1,0,2,YBK Jaiswal,Mohammed Shami,JC Buttler,legbyes,0,1,1,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
2,1312200,Rajasthan RoyalsGujarat Titans,1,0,3,JC Buttler,Mohammed Shami,YBK Jaiswal,NaN,1,0,1,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
3,1312200,Rajasthan RoyalsGujarat Titans,1,0,4,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
4,1312200,Rajasthan RoyalsGujarat Titans,1,0,5,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans

###`Q-6` Most Successful bowler against any batsman. Find that pair of bowler and batsman.
> Most Successful in terms of dissmissal. A bowler who have dissmissed any batsman most no of times. If any two pairs have same no of dissmisal, consider runs conceded by bowler to that batsman. Those who have concede lesser runs is more successful.

In [90]:
# code here
# code here

temp_df = ipl.groupby(['batter','bowler'])
temp_df['isWicketDelivery'].sum().sort_values(ascending=False).reset_index()

          batter            bowler  isWicketDelivery
0      RG Sharma         SP Narine                 8
1       MS Dhoni           PP Ojha                 7
2        V Kohli    Sandeep Sharma                 7
3       MS Dhoni            Z Khan                 7
4       PA Patel           B Kumar                 7
...          ...               ...               ...
24208     Z Khan  RN ten Doeschate                 0
24209     Z Khan          R Ashwin                 0
24210     Z Khan            P Negi                 0
24211     Z Khan           P Kumar                 0
24212     Z Khan         LR Shukla                 0

[24213 rows x 3 columns]

In [102]:
temp_df = ipl.groupby(['batter','bowler'])[['isWicketDelivery','total_run']].sum().sort_values(by = ['isWicketDelivery','total_run'], ascending=[False, True]).reset_index()
# temp_df[['batter', 'bowler']].head(5)
temp_df.head(10)

       batter          bowler  isWicketDelivery  total_run
0   RG Sharma       SP Narine                 8        140
1    PA Patel         B Kumar                 7         72
2    MS Dhoni          Z Khan                 7         78
3     V Kohli  Sandeep Sharma                 7         79
4   RG Sharma        A Mishra                 7         87
5    MS Dhoni         PP Ojha                 7        102
6  RV Uthappa        R Ashwin                 7        127
7   RG Sharma   R Vinay Kumar                 6         25
8   Q de Kock       YS Chahal                 6         44
9   RG Sharma      SK Trivedi                 6         46

###`Q-7`: Most successful batting pair in IPL. Batting pair who have scored most runs playing together.

In [108]:
# code here
batting_duo = ipl.groupby(['batter', 'non-striker'])['total_run'].sum().sort_values(ascending=False)
batting_duo.head(1)

batter          non-striker
AB de Villiers  V Kohli        1623
Name: total_run, dtype: int64

###`Q-8:` Make a dataframe for all batting pairs played together.
```
Batsman1 Batsman2 Runs Avg StrikeRate
```

> Just to ease this question you can count wide-balls for strike rate.

In [152]:
# code here
dfs = {
    'Batsman1' :[],
    'Batsman2' : [],
    'Runs' : [],
    'Avg' : [],
    'StrikeRate' : []
}

batting_duo = ipl.groupby(['batter', 'non-striker'])

for (b1,b2), data in batting_duo:

  runs = data['total_run'].sum()

  dfs['Batsman1'].append(b1)
  dfs['Batsman2'].append(b2)
  dfs['Runs'].append(runs)
  dfs['Avg'].append((runs / data.shape[0]).round(2))
  dfs['StrikeRate'].append((data['extra_type'] == 'wides').sum())

new_df = pd.DataFrame(dfs).sort_values(by = 'Runs', ascending=False).reset_index(drop=True)
new_df.head(10)

         Batsman1        Batsman2  Runs   Avg  StrikeRate
0  AB de Villiers         V Kohli  1623  1.57          17
1        CH Gayle         V Kohli  1617  1.61          50
2         V Kohli  AB de Villiers  1511  1.47          24
3       DA Warner        S Dhawan  1420  1.52          28
4         V Kohli        CH Gayle  1185  1.23          25
5      RV Uthappa       G Gambhir  1077  1.45          23
6        S Dhawan       DA Warner   937  1.19          22
7        CH Gayle        KL Rahul   909  1.41          29
8      MA Agarwal        KL Rahul   906  1.54          21
9       G Gambhir      RV Uthappa   829  1.22          20

In [157]:
# code here
dfs = {
    'Batsman1' :[],
    'Batsman2' : [],
    'Runs' : [],
    'Avg' : [],
    'StrikeRate' : []
}

batting_duo = ipl.groupby(['batter', 'non-striker'])

for (b1,b2), data in batting_duo:

  runs = data['total_run'].sum()
  balls = len(data) - (data['extra_type'] == 'wides').sum() # without wide ball
  strike_rate = (runs / balls * 100).round(2) if balls > 0 else 0

  dfs['Batsman1'].append(b1)
  dfs['Batsman2'].append(b2)
  dfs['Runs'].append(runs)
  dfs['Avg'].append((runs / data.shape[0]).round(2))
  dfs['StrikeRate'].append(strike_rate)

new_df = pd.DataFrame(dfs).sort_values(by = 'Runs', ascending=False).reset_index(drop=True)
new_df.tail(10)

/tmp/ipython-input-534925174.py:16: RuntimeWarning: divide by zero encountered in scalar divide
  strike_rate = (runs / balls * 100).round(2)

        Batsman1     Batsman2  Runs  Avg  StrikeRate
8052   RD Chahar    SS Tiwary     0  0.0         0.0
8053    UT Yadav      GB Hogg     0  0.0         0.0
8054   IK Pathan      S Sohal     0  0.0         0.0
8055    ND Doshi      SW Tait     0  0.0         0.0
8056      N Rana     UT Yadav     0  0.0         0.0
8057      P Negi   TG Southee     0  0.0         0.0
8058   KM Jadhav     AF Milne     0  0.0         0.0
8059     KK Nair     K Rabada     0  0.0         0.0
8060  SP Jackson  SW Billings     0  0.0         0.0
8061      Z Khan    S Aravind     0  0.0         0.0